# -*- coding: utf-8 -*-
"""DataProcess integration tests."""

import time
import random

from .. import (
    TestIntegration,
    get_default_client,
    get_vectors_client,
    random_bucket_name,
    random_short_bucket_name,
    ACCESS_ID,
    ACCESS_KEY,
    REGION,
    ENDPOINT,
    USER_ID,
)

import alibabacloud_oss_v2 as oss
import alibabacloud_oss_v2.dataprocess as oss_dataprocess


DATASET_NAME_PREFIX = 'test-dp-dataset-'

# If TEST_DATAPROCESS_BUCKET is set, data process tests run against that
# existing bucket; otherwise the bucket created by the integration base
# class is used.
TEST_DATAPROCESS_BUCKET = 'examplebucket-test'

ROLE = 'AliyunMetaQueryDefaultRole'


def get_dataprocess_client() -> oss_dataprocess.Client:
    cfg = oss.config.load_default()
    cfg.credentials_provider = oss.credentials.StaticCredentialsProvider(ACCESS_ID, ACCESS_KEY)
    cfg.region = REGION
    cfg.endpoint = ENDPOINT
    cfg.account_id = USER_ID
    return oss_dataprocess.Client(cfg)


def gen_dataset_name():
    """Generate a random dataset name for testing."""
    return DATASET_NAME_PREFIX + str(int(time.time() * 1000)) + '-' + str(random.randint(0, 9999))


def wait_for_cache_expiration(duration_seconds: int):
    """Sleep for the given seconds, aligned with Java TestBase.waitForCacheExpiration."""
    time.sleep(duration_seconds)


def open_meta_query_quietly(client: oss_dataprocess.Client, bucket: str, mode: str = 'semantic', role: str = ROLE):
    """Open meta query with specified mode, ignoring errors if already open."""
    try:
        client.open_meta_query(oss_dataprocess.models.OpenMetaQueryRequest(
            bucket=bucket,
            mode=mode,
            role=role
        ))
    except Exception:
        pass


def close_meta_query_quietly(client: oss_dataprocess.Client, bucket: str):
    """Close meta query on the bucket in a best-effort manner."""
    try:
        client.close_meta_query(oss_dataprocess.models.CloseMetaQueryRequest(
            bucket=bucket,
        ))
    except Exception:
        pass


def find_service_error(exc: Exception):
    """Walk the exception chain and return the underlying ServiceError, or None."""
    cur = exc
    while cur is not None:
        if isinstance(cur, oss.exceptions.ServiceError):
            return cur
        cur = getattr(cur, 'unwrap', lambda: None)() if hasattr(cur, 'unwrap') else cur.__cause__
    return None


def collect_error_messages(exc: Exception) -> str:
    """Concatenate messages along the exception chain for assertion."""
    messages = []
    cur = exc
    while cur is not None:
        if str(cur):
            messages.append(str(cur))
        cur = getattr(cur, 'unwrap', lambda: None)() if hasattr(cur, 'unwrap') else cur.__cause__
    return '\n'.join(messages)


class TestBaseDataProcess(TestIntegration):
    # Whether to open meta query during class setup.
    # Data pipeline tests do not need meta query to be opened.
    open_meta_query_on_setup = True

    @classmethod
    def setup_assertions(cls):
        """Return a TestCase instance hosting assertion calls in setUpClass.

        unittest assertion methods are instance methods, so calling them
        via cls inside a classmethod raises TypeError. A throwaway instance
        is constructed here so setUpClass can still use assertIsNotNone /
        assertEqual and friends.
        """
        return cls('setUpClass')

    @classmethod
    def setUpClass(cls):
        TestIntegration.setUpClass()
        cls.dp_client = get_dataprocess_client()
        if TEST_DATAPROCESS_BUCKET:
            cls.dp_bucket = TEST_DATAPROCESS_BUCKET
        else:
            cls.dp_bucket = cls.bucket_name
        # Dataset generated by the base class, cleaned up in tearDownClass.
        cls.dp_dataset_name = gen_dataset_name()
        if cls.open_meta_query_on_setup:
            open_meta_query_quietly(cls.dp_client, cls.dp_bucket, 'semantic', ROLE)

    @classmethod
    def tearDownClass(cls):
        close_meta_query_quietly(cls.dp_client, cls.dp_bucket)

        # Clean up the dataset generated by the base class.
        if getattr(cls, 'dp_client', None) is not None and getattr(cls, 'dp_dataset_name', None) is not None:
            try:
                cls.dp_client.delete_dataset(
                    oss_dataprocess.models.DeleteDatasetRequest(
                        bucket=cls.dp_bucket,
                        dataset_name=cls.dp_dataset_name,
                    )
                )
            except Exception:
                pass
        TestIntegration.tearDownClass()
